matrix:
    include:
      - language: python
        python: "3.6"
        script: make tests-py-coverage
        addons:
            postgresql: "9.6"
        before_script:
            - psql -c 'create database inboxenTest;' -U postgres
            - psql -c 'SELECT version();' -U postgres
        after_script:
          - pip install codecov
          - codecov

      - language: python
        python: "3.6"
        env: TOX_ENV=lint,isort

      - language: python
        python: "3.6"
        env: TOX_ENV=docs

      - language: node_js
        node_js: "8"
        env:
          - GRUNT_TASK=karma:firefox
          - MOZ_HEADLESS=1
          - FIREFOX=esr
        after_script:
          - npm install codecov
          - npx codecov
        addons:
            firefox: latest-esr

      - language: node_js
        node_js: "8"
        env:
          - GRUNT_TASK=karma:firefox
          - MOZ_HEADLESS=1
          - FIREFOX=latest
        after_script:
          - npm install codecov
          - npx codecov
        addons:
            firefox: latest

      - language: node_js
        node_js: "8"
        env: GRUNT_TASK=karma:chrome
        after_script:
          - npm install codecov
          - npx codecov
        addons:
            chrome: stable
      - language: node_js
        node_js: "8"
        env: GRUNT_TASK=jshint

install: if [[ $TOX_ENV ]]; then pip install tox; elif [[ $GRUNT_TASK ]]; then npm install; fi
script: if [[ $TOX_ENV ]]; then tox -e $TOX_ENV; elif [[ $GRUNT_TASK ]]; then npx grunt $GRUNT_TASK; fi

sudo: false
