language: python
python:
    - "2.7"

env:
    - DB=sqlite
    - DB=postgres

before_script:
  - psql -c 'create database inboxen;' -U postgres

install:
    - mkdir node_modules
    - travis_retry npm update
    - if [[ $DB == postgres ]]; then travis_retry pip install -q psycopg2; fi
    - travis_retry pip install -q -r requirements.txt
    - travis_retry pip install -q codecov
    - travis_retry gem install sass
    - python manage.py collectstatic --noinput --settings=inboxen.tests.settings

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV

script: coverage run manage.py test --settings=inboxen.tests.settings
after_success: codecov

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
