language: python
python:
    - "2.7"

env:
    - DB=sqlite
    - DB=postgres

before_script:
  - psql -c 'create database inboxen;' -U postgres

install:
    - if [[ $DB == postgres ]]; then travis_retry pip install -q psycopg2; fi
    - travis_retry pip install -q -r requirements.txt
    - travis_retry pip install coveralls
    - python manage.py collectstatic --noinput --settings=inboxen.tests.settings

script: coverage run manage.py test --settings=inboxen.tests.settings
after_success: coveralls

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
